version: '3'
services:
  # mongo:
  #   image: "mongo:4.2"
  #   ports:
  #     - "${MONGO_PORT}:${MONGO_PORT}"
  #   env_file:
  #     - .env
  # redis:
  #   image: "redis:rc-alpine3.12"
  #   command: redis-server --requirepass ${REDIS_PWD}
  #   ports:
  #     - "${REDIS_PORT}:${REDIS_PORT}"
  #   env_file:
  #     - .env
  server:
    ports:
      - ${PORT}:${PORT}
    image: ${DOCKER_HUB_USERNAME}/${APP_NAME}:${APP_VER}
    container_name: ${APP_NAME}
    build:
      dockerfile: Dockerfile
      context: ./
      target: dev
    stdin_open: true #keep connection unitl compling source done
    environment:
      MONGODB: ${MONGODB} #export in container for using in third-party service
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules/ #fix node-sass not working
    # depends_on:
    #   - mongo
    #   - redis
