version: "3"
services:
  # mongo:
  #   image: "mongo:4.2"
  #   ports:
  #     - "${MONGO_PORT}:${MONGO_PORT}"
  #   env_file:
  #     - .env
  # redis:
  #   image: "redis:rc-alpine3.12"
  #   command: redis-server --requirepass ${REDIS_PWD}
  #   ports:
  #     - "${REDIS_PORT}:${REDIS_PORT}"
  #   env_file:
  #     - .env
  server:
    ports:
      - "${APP_PORT}:${APP_PORT}"
    image: "app:${APP_VER}"
    build:
      dockerfile: Dockerfile
      context: ./
      target: dev
    stdin_open: true
    environment:
      APP_PORT: 9090
    env_file:
      - .env
    volumes:
      - .:/app
    # depends_on:
    #   - mongo
    #   - redis