version: '3'
services:
  # mongo:
  #   image: "mongo:4.2"
  #   ports:
  #     - "${MONGO_PORT}:${MONGO_PORT}"
  #   env_file:
  #     - .env
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8001:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/api.yaml
  server:
    ports:
      - ${PORT}:${PORT}
    image: ${DOCKER_HUB_USERNAME}/${APP_NAME}:${APP_VER}
    container_name: ${APP_NAME}
    build:
      dockerfile: Dockerfile
      context: ./
      target: dev
    stdin_open: true #keep connection unitl compling source done
    environment:
      MONGODB: ${MONGODB} #export in container for using in third-party service
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules/ #fix node-sass not working
    depends_on:
      - swagger-ui
